/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/model.gltf')
  return (
    <group position={[0, 0, 0]} scale={[2, 2, 2]} ref={group} {...props}>
      <mesh material={materials.BlocksPaper} geometry={nodes['node_MeshObject-98158592-PolyPaper21'].geometry} />
    </group>
  )
}

useGLTF.preload('/model.gltf')
