export const TIME_TO_CHOOSE = 5000
export const YOUR_SELECTION_NOT_SELECTED = 4

export const MODEL_OUTSIDE_POSITION_TOP = [0, 4, 0]
export const MODEL_OUTSIDE_POSITION_BOTTOM = [0, -9, 0]

export const CONTROL_REVEAL_TRANSITION_DURATION = 500
